name: build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ВАЖНО: указываем SDK туда, где его ждёт Buildozer
      - name: Define SDK env paths
        shell: bash
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV

      - name: Create venv & install Buildozer/p4a
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install "buildozer==1.5.0" "python-for-android==2024.01.21" "Cython<3.0" "wheel" "setuptools<70"

      - name: Install Android commandline-tools (sdkmanager)
        shell: bash
        run: |
          set -eux
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL -o "$RUNNER_TEMP/cmdtools.zip" \
            "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
          unzip -q "$RUNNER_TEMP/cmdtools.zip" -d "$RUNNER_TEMP/cmdtools"
          mv "$RUNNER_TEMP/cmdtools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          # Добавим в PATH для следующих шагов
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/36.0.0" >> $GITHUB_PATH

      - name: Accept licenses & install SDK packages
        shell: bash
        run: |
          set -eux
          SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          # Принять лицензии (Broken pipe от 'yes' игнорируем)
          yes | "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
          # Установка нужных пакетов
          "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" "platforms;android-34" "build-tools;36.0.0"

      - name: Build APK (debug)
        shell: bash
        run: |
          set -eux
          source venv/bin/activate
          # Не чистим, если p4a ещё не скачан
          if [ -d "$HOME/.buildozer/android/platform/python-for-android" ]; then
            python -m buildozer -v android clean
          fi
          python -m buildozer -v android debug

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: calculator-debug-apk
          path: bin/*.apk
