name: build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Create venv & install Buildozer toolchain
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install "buildozer==1.5.0" "python-for-android==2024.01.21" "Cython<3.0" "wheel" "setuptools<70"

      - name: Install Android commandline-tools (sdkmanager)
        run: |
          set -euxo pipefail
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL -o "$RUNNER_TEMP/cmdtools.zip" \
            "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
          unzip -q "$RUNNER_TEMP/cmdtools.zip" -d "$RUNNER_TEMP/cmdtools"
          mv "$RUNNER_TEMP/cmdtools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/36.0.0" >> $GITHUB_PATH

      - name: Accept licenses & install SDK packages
        run: |
          set -euxo pipefail
          SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKMANAGER" --licenses --sdk_root="$ANDROID_SDK_ROOT" || true
          "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" "platforms;android-34" "build-tools;36.0.0"

      - name: Build APK (debug)
        run: |
          set -euxo pipefail
          source venv/bin/activate
          if [ -d ".buildozer/android/platform/python-for-android" ]; then
            python -m buildozer -v android clean
          fi
          python -m buildozer -v android debug

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: calculator-debug-apk
          path: bin/*.apk
